	! Common module for each instance of IBR_Control model
	! Generated by IEC DLL PSCAD Import tool version 1.0
	! Wrapper structure matches ext_simenv_capi.h: Model_Instance() is the DLL-owned
	! instance allocator, and ExtU_DISCON_Empty_T / ExtY_DISCON_Empty_T / P_DISCON_Empty_T
	! are flat real64 arrays inside that DLL-owned instance -- not Fortran-side structs.
	MODULE IBR_Control_MOD

	USE, INTRINSIC :: iso_c_binding
	USE IFWIN ! To use INTEGER(handle)

	INTEGER(handle) :: dllHandle = 0 ! Handle to the DLL
	DOUBLE PRECISION :: EQUALITY_PRECISION = 1.0d-12  ! Used to test equality
	! between two double variables
	LOGICAL :: FIRST_CALL_THIS_FILE = .TRUE.  ! Used to allocate some arrays
	! and set pointers to DLL functions
	DOUBLE PRECISION   :: DELT_Model      ! The sampling time (Sec) needed by this model
	INTEGER :: N_INSTANCE = 0  ! nb instances of this specific IEEE CIGRE Model,
	! useful at last time-step to use FreeLibrary
	INTEGER :: N_CALL_LAST_STEP = 0  ! nb call at last step, useful at last
	! time-step to use FreeLibrary
	INTEGER   :: IUNIT = 6 ! Unit to use for Write Statements
	CHARACTER*11   :: OrigModelName = "IBR_Control"  ! Model name, written by the DLL Import tool

	! Number of scalar signals in THIS model (order must match the flat
	! ExtU/ExtY/P arrays of the DLL -- i.e. the order used when the DLL was built).
	! CHARACTER(*) parameters, if any, are excluded from N_PARAMETERS: the
	! Ext-SimEnv C API only supports numeric parameters in the flat P array.
	INTEGER, PARAMETER :: N_INPUTS     = 6
	INTEGER, PARAMETER :: N_OUTPUTS    = 3
	INTEGER, PARAMETER :: N_PARAMETERS = 15

	!---------------------------------
	!--- Types common to each model, mirroring ext_simenv_capi.h -------
	!---------------------------------
	TYPE, BIND(C) :: ESEExtension
		INTEGER(c_int64_t) :: raw   ! 8-byte union placeholder, content unused here
	END TYPE

	TYPE, BIND(C) :: StaticExtSimEnvCapi
		INTEGER(c_int8_t)  :: APIRelease(4)
		TYPE(c_ptr)        :: ModelName
		TYPE(c_ptr)        :: ModelVersion
		TYPE(c_ptr)        :: ModelDescription
		TYPE(c_ptr)        :: VersionControlInfo
		TYPE(c_ptr)        :: GeneralInformation
		TYPE(c_ptr)        :: ModelCreated
		TYPE(c_ptr)        :: ModelCreator
		TYPE(c_ptr)        :: ModelLastModifiedDate
		TYPE(c_ptr)        :: ModelLastModifiedBy
		TYPE(c_ptr)        :: ModelModifiedComment
		TYPE(c_ptr)        :: ModelModifiedHistory
		TYPE(c_ptr)        :: CodeGeneratedOn
		TYPE(c_ptr)        :: IncludedSolver
		REAL(c_double)     :: FixedStepBaseSampleTime
		INTEGER(c_int32_t) :: NumInputPorts
		TYPE(c_ptr)        :: InputPortsInfo
		INTEGER(c_int32_t) :: NumOutputPorts
		TYPE(c_ptr)        :: OutputPortsInfo
		INTEGER(c_int32_t) :: NumParameters
		TYPE(c_ptr)        :: ParametersInfo
		INTEGER(c_int32_t) :: NumContStates
		INTEGER(c_int32_t) :: SizeofMiscStates
		INTEGER(c_int32_t) :: ModelChecksum(4)
		TYPE(c_ptr)        :: LastErrorMessage
		INTEGER(c_int8_t)  :: EMT_RMS_Mode
		INTEGER(c_int8_t)  :: LoadflowFlag
		TYPE(ESEExtension) :: Extension
	END TYPE

	! Instance-specific struct, ALLOCATED AND OWNED BY THE DLL. We only
	! ever hold a c_ptr to one of these -- never a Fortran-side copy.
	TYPE, BIND(C) :: InstanceExtSimEnvCapi
		TYPE(c_ptr)        :: ExtU_DISCON_Empty_T   ! real64_T* (N_INPUTS)
		TYPE(c_ptr)        :: ExtY_DISCON_Empty_T   ! real64_T* (N_OUTPUTS)
		TYPE(c_ptr)        :: P_DISCON_Empty_T      ! real64_T* (N_PARAMETERS)
		TYPE(c_ptr)        :: ContinuousStates
		TYPE(c_ptr)        :: StateDerivatives
		TYPE(c_ptr)        :: MiscStates
		TYPE(c_ptr)        :: LastErrorMessage
		TYPE(c_ptr)        :: LastGeneralMessage
		INTEGER(c_int8_t)  :: VerboseLevel
		TYPE(ESEExtension) :: Extension
	END TYPE

	!----------------------------------
	!--- Interface to DLL functions ---
	!----------------------------------
	! pInstanceCapi is passed BY VALUE (it is already a pointer, exactly as the
	! C prototype "InstanceExtSimEnvCapi *pInstanceCapi" expects). All functions
	! except Model_GetInfo/Model_Instance return a char* message pointer:
	! c_null_ptr = OK, otherwise a pointer to an error string.
	INTERFACE
		FUNCTION Model_GetInfo()
			IMPORT :: c_ptr
			!DEC$ ATTRIBUTES C :: Model_GetInfo
			TYPE(c_ptr) :: Model_GetInfo
		END FUNCTION

		FUNCTION Model_Instance(UseSolverInDLL, Ta)
			IMPORT :: c_ptr, c_int32_t, c_double
			!DEC$ ATTRIBUTES C :: Model_Instance
			!DEC$ ATTRIBUTES VALUE :: UseSolverInDLL, Ta
			INTEGER(c_int32_t), INTENT(IN) :: UseSolverInDLL
			REAL(c_double), INTENT(IN) :: Ta
			TYPE(c_ptr) :: Model_Instance
		END FUNCTION

		FUNCTION Model_CheckParameters(pInstanceCapi)
			IMPORT :: c_ptr
			!DEC$ ATTRIBUTES C :: Model_CheckParameters
			!DEC$ ATTRIBUTES VALUE :: pInstanceCapi
			TYPE(c_ptr), INTENT(IN) :: pInstanceCapi
			TYPE(c_ptr) :: Model_CheckParameters
		END FUNCTION

		FUNCTION Model_Initialize(pInstanceCapi)
			IMPORT :: c_ptr
			!DEC$ ATTRIBUTES C :: Model_Initialize
			!DEC$ ATTRIBUTES VALUE :: pInstanceCapi
			TYPE(c_ptr), INTENT(IN) :: pInstanceCapi
			TYPE(c_ptr) :: Model_Initialize
		END FUNCTION

		FUNCTION Model_Outputs(pInstanceCapi, IsMajorTimeStep)
			IMPORT :: c_ptr, c_int32_t
			!DEC$ ATTRIBUTES C :: Model_Outputs
			!DEC$ ATTRIBUTES VALUE :: pInstanceCapi, IsMajorTimeStep
			TYPE(c_ptr), INTENT(IN) :: pInstanceCapi
			INTEGER(c_int32_t), INTENT(IN) :: IsMajorTimeStep
			TYPE(c_ptr) :: Model_Outputs
		END FUNCTION

		FUNCTION Model_Update(pInstanceCapi)
			IMPORT :: c_ptr
			!DEC$ ATTRIBUTES C :: Model_Update
			!DEC$ ATTRIBUTES VALUE :: pInstanceCapi
			TYPE(c_ptr), INTENT(IN) :: pInstanceCapi
			TYPE(c_ptr) :: Model_Update
		END FUNCTION

		FUNCTION Model_Terminate(pInstanceCapi)
			IMPORT :: c_ptr
			!DEC$ ATTRIBUTES C :: Model_Terminate
			!DEC$ ATTRIBUTES VALUE :: pInstanceCapi
			TYPE(c_ptr), INTENT(IN) :: pInstanceCapi
			TYPE(c_ptr) :: Model_Terminate
		END FUNCTION
	END INTERFACE

	! Function pointers, resolved at runtime via GetProcAddress (DLL_Path is
	! chosen by the PSCAD component, so late binding is kept as before)
	POINTER(pointer_Model_GetInfo,         Model_GetInfo)
	POINTER(pointer_Model_Instance,        Model_Instance)
	POINTER(pointer_Model_CheckParameters, Model_CheckParameters)
	POINTER(pointer_Model_Initialize,      Model_Initialize)
	POINTER(pointer_Model_Outputs,         Model_Outputs)
	POINTER(pointer_Model_Update,          Model_Update)
	POINTER(pointer_Model_Terminate,       Model_Terminate)

	contains

		! Checks a returned char* message pointer. NULL => OK, else print & stop.
		subroutine Handle_Message(context, msg_cptr)
			implicit none
			CHARACTER(*), INTENT(IN) :: context
			TYPE(c_ptr), INTENT(IN) :: msg_cptr
			CHARACTER(:), ALLOCATABLE :: msg

			IF (c_associated(msg_cptr)) THEN
				msg = Get_Fortran_String(msg_cptr)
				IF (LEN(msg) .GT. 0) THEN
					WRITE(IUNIT,*) "Error in ", trim(context), ": ", msg
				ELSE
					WRITE(IUNIT,*) "Unspecified error in ", trim(context)
				ENDIF
				FLUSH(IUNIT)
				STOP  ! Stop the simulation
			ENDIF
		end subroutine

		subroutine Get_DLL_Handle(DLL_Path)
			use, intrinsic :: iso_c_binding, only : c_null_char
			implicit none
			character*(*), INTENT(IN) :: DLL_Path
			dllHandle = LoadLibrary(trim(DLL_Path) // C_NULL_CHAR)
			if (dllHandle .eq. 0) then
				WRITE(IUNIT,*) "*** Error loading ", trim(DLL_Path)
				STOP
			endif
		end subroutine

		subroutine Get_Pointer_To_DLL_Function(functionName, functionAd)
			use, intrinsic :: iso_c_binding, only : c_null_char
			implicit none
			character*(*), INTENT(IN) :: functionName
			integer(handle), INTENT(INOUT) :: functionAd
			functionAd = GetProcAddress(dllHandle, trim(functionName)// C_NULL_CHAR)
			if (functionAd .eq. 0) then
				WRITE(IUNIT,*) "*** Error finding DLL function ", trim(functionName)
				stop
			endif
		end subroutine

		function Get_Fortran_String(c_input) result(output)
			use, intrinsic :: iso_c_binding, only : c_ptr, c_f_pointer, c_null_char, c_associated
			implicit none
			TYPE(c_ptr), INTENT(IN) :: c_input
			character(:), allocatable :: output
			character(10000), pointer :: string_fp
			integer string_length
			output = ""
			if (c_associated(c_input)) then
				call c_f_pointer(c_input, string_fp)
				string_length = index(string_fp, c_null_char)
				if (string_length .ne. 0) then
					output = string_fp(1:string_length-1)
				endif
			endif
			return
		end function

		! --- Helpers to persist a c_ptr (64-bit address) across time steps ---
		! The per-instance STORI array (PSCAD) holds INTEGER(4) slots, so a pointer
		! needs 2 slots on a 64-bit build.
		function CPtr_To_Ints(cptr_in) result(ints)
			implicit none
			TYPE(c_ptr), INTENT(IN) :: cptr_in
			INTEGER :: ints(2)
			INTEGER(c_intptr_t) :: addr
			addr = TRANSFER(cptr_in, addr)
			ints = TRANSFER(addr, ints)
		end function

		function Ints_To_CPtr(ints) result(cptr_out)
			implicit none
			INTEGER, INTENT(IN) :: ints(2)
			TYPE(c_ptr) :: cptr_out
			INTEGER(c_intptr_t) :: addr
			addr = TRANSFER(ints, addr)
			cptr_out = TRANSFER(addr, cptr_out)
		end function

	END MODULE IBR_Control_MOD



	SUBROUTINE IBR_Control_FINTERFACE_PSCAD(&
	    in_voltage_a_pscad, in_voltage_b_pscad, in_voltage_c_pscad, in_current_a_pscad, in_current_b_pscad, &
	    in_current_c_pscad, Fn_pscad, Iang0_pcc_pscad, Imag0_pcc_pscad, Ki_I_pscad, &
	    Ki_PLL_pscad, Kp_I_pscad, Kp_PLL_pscad, Lc_pscad, Pref_pscad, &
	    Qref_pscad, Rc_pscad, Tf_S_pscad, Ts_pscad, Vang0_pcc_pscad, &
	    Vmag0_pcc_pscad, out_voltage_a_pscad, out_voltage_b_pscad, out_voltage_c_pscad, out_voltage_a_init_pscad, &
	    out_voltage_b_init_pscad, out_voltage_c_init_pscad, TRelease, DLL_Path, Use_Interpolation)


	USE, INTRINSIC :: iso_c_binding

	USE IBR_Control_MOD

	INCLUDE 's1.h' ! This include gives us access to TIME, TIMEZERO etc. variables
	INCLUDE 'emtstor.h' ! This include gives us access to STORI, STORF, NSTORI, NSTORF

	IMPLICIT NONE

	! Inputs, params and outputs variables, received from PSCAD
	REAL, INTENT(IN) :: in_voltage_a_pscad
	REAL, INTENT(IN) :: in_voltage_b_pscad
	REAL, INTENT(IN) :: in_voltage_c_pscad
	REAL, INTENT(IN) :: in_current_a_pscad
	REAL, INTENT(IN) :: in_current_b_pscad
	REAL, INTENT(IN) :: in_current_c_pscad

	REAL, INTENT(IN) :: Fn_pscad
	REAL, INTENT(IN) :: Iang0_pcc_pscad
	REAL, INTENT(IN) :: Imag0_pcc_pscad
	REAL, INTENT(IN) :: Ki_I_pscad
	REAL, INTENT(IN) :: Ki_PLL_pscad
	REAL, INTENT(IN) :: Kp_I_pscad
	REAL, INTENT(IN) :: Kp_PLL_pscad
	REAL, INTENT(IN) :: Lc_pscad
	REAL, INTENT(IN) :: Pref_pscad
	REAL, INTENT(IN) :: Qref_pscad
	REAL, INTENT(IN) :: Rc_pscad
	REAL, INTENT(IN) :: Tf_S_pscad
	REAL, INTENT(IN) :: Ts_pscad
	REAL, INTENT(IN) :: Vang0_pcc_pscad
	REAL, INTENT(IN) :: Vmag0_pcc_pscad

	REAL, INTENT(IN) :: out_voltage_a_init_pscad
	REAL, INTENT(IN) :: out_voltage_b_init_pscad
	REAL, INTENT(IN) :: out_voltage_c_init_pscad

	REAL, INTENT(OUT) :: out_voltage_a_pscad
	REAL, INTENT(OUT) :: out_voltage_b_pscad
	REAL, INTENT(OUT) :: out_voltage_c_pscad

	! Other inputs
	DOUBLE PRECISION, INTENT(IN) :: TRelease  ! Time to release initial output values
	CHARACTER*(*), INTENT(IN) :: DLL_Path
	LOGICAL, INTENT(IN) :: Use_Interpolation  ! if inputs interpolation is
	! checked in the PSCAD component form

	! --------------------------------
	! Local variables
	! --------------------------------
	INTEGER :: i  ! Used for loops
	INTEGER :: retValFreeLib     ! Only for FreeLibrary
	TYPE(c_ptr) :: pInstanceCapi        ! opaque handle owned by the DLL
	TYPE(InstanceExtSimEnvCapi), POINTER :: pInstanceCapi_fp
	REAL(c_double), POINTER :: ExtU(:), ExtY(:), P(:)
	TYPE(c_ptr) :: msg_cptr

	DOUBLE PRECISION :: Next_t_model ! To know when to call model output function
	INTEGER :: Step_Count_Model ! Counter to calculate Next_t_model without
	! numerical drift
	LOGICAL   :: First_Step_Model ! To know the first time model sampling time
	! has been reached
	TYPE(c_ptr)                                           :: Model_Info_cp
	! The C pointer of Model_GetInfo
	TYPE(StaticExtSimEnvCapi), POINTER     :: Model_Info_fp ! The F pointer of Model_GetInfo
	INTEGER(KIND=c_int8_t), DIMENSION(4) :: OrigDLLInterfaceVersion = [0, 8, 1, 5]  ! DLL interface version, written by the DLL Import tool
	! Variables for interpolation
	DOUBLE PRECISION :: Prev_t_pscad  ! Previous PSCAD time
	DOUBLE PRECISION ::delta_t1  ! Used to calculate interpolated inputs
	DOUBLE PRECISION ::delta_t2  ! Used to calculate interpolated inputs
	REAL :: in_voltage_a_pscad_prev
	REAL :: in_voltage_b_pscad_prev
	REAL :: in_voltage_c_pscad_prev
	REAL :: in_current_a_pscad_prev
	REAL :: in_current_b_pscad_prev
	REAL :: in_current_c_pscad_prev

	INTEGER :: idx_start_outputs           ! STORF: cached last outputs (N_OUTPUTS)
	INTEGER :: idx_start_prev_t            ! STORF start index to store Prev_t_pscad
	INTEGER :: idx_start_inputs            ! STORF start index to store inputs
	INTEGER :: idx_start_next_model_storf  ! STORF start index for the next model
	INTEGER :: idx_start_first_step_model  ! STORI: flag
	INTEGER :: idx_start_step_count_model  ! STORI: step counter
	INTEGER :: idx_start_instance_ptr      ! STORI: 2 slots holding the c_ptr bits
	INTEGER :: idx_start_next_model_stori  ! STORI start index for the next model

	! --------------------------------
	! Load the DLL once for the whole simulation (shared across instances)
	! --------------------------------
	IF (FIRST_CALL_THIS_FILE) THEN

		CALL Get_DLL_Handle(DLL_Path)

		CALL Get_Pointer_To_DLL_Function("Model_GetInfo",         pointer_Model_GetInfo)
		CALL Get_Pointer_To_DLL_Function("Model_Instance",        pointer_Model_Instance)
		CALL Get_Pointer_To_DLL_Function("Model_CheckParameters", pointer_Model_CheckParameters)
		CALL Get_Pointer_To_DLL_Function("Model_Initialize",      pointer_Model_Initialize)
		CALL Get_Pointer_To_DLL_Function("Model_Outputs",         pointer_Model_Outputs)
		CALL Get_Pointer_To_DLL_Function("Model_Update",          pointer_Model_Update)
		CALL Get_Pointer_To_DLL_Function("Model_Terminate",       pointer_Model_Terminate)

		Model_Info_cp = Model_GetInfo()
		IF (.NOT. c_associated(Model_Info_cp)) THEN
			WRITE(IUNIT,*) "*** Error: Model_GetInfo returned NULL"
			STOP
		ENDIF
		call c_f_pointer(Model_Info_cp, Model_Info_fp)

		DELT_Model = Model_Info_fp%FixedStepBaseSampleTime
		IF (DELT_Model .EQ. -1) THEN
			DELT_Model = DELT
		ENDIF

		DO i = 1, 4
			IF (Model_Info_fp%APIRelease(i) /= OrigDLLInterfaceVersion(i)) THEN
				WRITE(IUNIT,*) "*** Warning - DLL interface version mismatch. Continuing anyway."
				EXIT
			END IF
		END DO

		FIRST_CALL_THIS_FILE = .FALSE.
	ENDIF
	! --------------------------------
	! Initialize STORF start indexes
	! --------------------------------
	idx_start_outputs          = NSTORF
	idx_start_prev_t            = idx_start_outputs + N_OUTPUTS
	idx_start_inputs            = idx_start_prev_t + 1
	idx_start_next_model_storf  = idx_start_inputs + N_INPUTS

	! --------------------------------
	! Initialize STORI start indexes
	! --------------------------------
	idx_start_first_step_model = NSTORI
	idx_start_step_count_model = idx_start_first_step_model + 1
	idx_start_instance_ptr     = idx_start_step_count_model + 1   ! uses 2 slots
	idx_start_next_model_stori = idx_start_instance_ptr + 2

	! --------------------------------
	! Restore per-instance state
	! --------------------------------
	First_Step_Model = (STORI(idx_start_first_step_model) /= 0)
	Step_Count_Model = STORI(idx_start_step_count_model)
	IF (TIMEZERO) Step_Count_Model = 0
	Next_t_model = Step_Count_Model * DELT_Model

	! FIRSTSTEP is True for first step starting from the Data file (so at T0) or Snapshot file.
	IF (FIRSTSTEP) THEN
		N_INSTANCE = N_INSTANCE + 1
		First_Step_Model = .TRUE.
	ENDIF

	! Check if the model sampling time has been reached
	! True at T0
	DO WHILE ( TIME .GE. Next_t_model - EQUALITY_PRECISION )

		! ---- Create the instance on the very first model step ----
		! NOTE: UseSolverInDLL = 1 asks the DLL to use its own internal solver;
		! pass 0 instead if the model should be integrated by PSCAD/an external solver.
		IF (First_Step_Model) THEN
			pInstanceCapi = Model_Instance(1_c_int32_t, DELT_Model)
			IF (.NOT. c_associated(pInstanceCapi)) THEN
				WRITE(IUNIT,*) "*** Error: Model_Instance returned NULL"
				STOP
			ENDIF
			STORI(idx_start_instance_ptr:idx_start_instance_ptr+1) = CPtr_To_Ints(pInstanceCapi)
			First_Step_Model = .FALSE.
		ELSE
			pInstanceCapi = Ints_To_CPtr(STORI(idx_start_instance_ptr:idx_start_instance_ptr+1))
		ENDIF

		! ---- Map the DLL-owned flat signal arrays ----
		call c_f_pointer(pInstanceCapi, pInstanceCapi_fp)
		call c_f_pointer(pInstanceCapi_fp%ExtU_DISCON_Empty_T, ExtU, [N_INPUTS])
		call c_f_pointer(pInstanceCapi_fp%ExtY_DISCON_Empty_T, ExtY, [N_OUTPUTS])
		call c_f_pointer(pInstanceCapi_fp%P_DISCON_Empty_T,    P,    [N_PARAMETERS])

		! Assign parameters from the simulation tool side to model parameters
		! Done every model step, before Model_CheckParameters/Model_Initialize
		P(1) = Fn_pscad
		P(2) = Iang0_pcc_pscad
		P(3) = Imag0_pcc_pscad
		P(4) = Ki_I_pscad
		P(5) = Ki_PLL_pscad
		P(6) = Kp_I_pscad
		P(7) = Kp_PLL_pscad
		P(8) = Lc_pscad
		P(9) = Pref_pscad
		P(10) = Qref_pscad
		P(11) = Rc_pscad
		P(12) = Tf_S_pscad
		P(13) = Ts_pscad
		P(14) = Vang0_pcc_pscad
		P(15) = Vmag0_pcc_pscad

		! ---- Write inputs (order must match the DLL input list) ----
		IF (Use_Interpolation .AND. .NOT. TIMEZERO) THEN
			delta_t1 = TIME - Prev_t_pscad
			delta_t2 = Next_t_model - Prev_t_pscad
			ExtU(1) = in_voltage_a_pscad_prev + (in_voltage_a_pscad - in_voltage_a_pscad_prev) * delta_t2 / delta_t1
			ExtU(2) = in_voltage_b_pscad_prev + (in_voltage_b_pscad - in_voltage_b_pscad_prev) * delta_t2 / delta_t1
			ExtU(3) = in_voltage_c_pscad_prev + (in_voltage_c_pscad - in_voltage_c_pscad_prev) * delta_t2 / delta_t1
			ExtU(4) = in_current_a_pscad_prev + (in_current_a_pscad - in_current_a_pscad_prev) * delta_t2 / delta_t1
			ExtU(5) = in_current_b_pscad_prev + (in_current_b_pscad - in_current_b_pscad_prev) * delta_t2 / delta_t1
			ExtU(6) = in_current_c_pscad_prev + (in_current_c_pscad - in_current_c_pscad_prev) * delta_t2 / delta_t1
		ELSE
			ExtU(1) = in_voltage_a_pscad
			ExtU(2) = in_voltage_b_pscad
			ExtU(3) = in_voltage_c_pscad
			ExtU(4) = in_current_a_pscad
			ExtU(5) = in_current_b_pscad
			ExtU(6) = in_current_c_pscad
		ENDIF

		IF (TIMEZERO) THEN
			msg_cptr = Model_CheckParameters(pInstanceCapi)
			call Handle_Message("Model_CheckParameters", msg_cptr)
		ENDIF

		IF (TIMEZERO .OR. (TIME .LE. TRelease)) THEN
			! Seed outputs with the mask-provided init values before Initialize
			ExtY(1) = out_voltage_a_init_pscad
			ExtY(2) = out_voltage_b_init_pscad
			ExtY(3) = out_voltage_c_init_pscad

			msg_cptr = Model_Initialize(pInstanceCapi)
			call Handle_Message("Model_Initialize", msg_cptr)
		ENDIF

		msg_cptr = Model_Outputs(pInstanceCapi, 1_c_int32_t)  ! 1 = major time step
		call Handle_Message("Model_Outputs", msg_cptr)

		msg_cptr = Model_Update(pInstanceCapi)
		call Handle_Message("Model_Update", msg_cptr)

		! ---- Cache outputs into STORF (read back even on PSCAD sub-steps) ----
		STORF(idx_start_outputs + 0) = REAL(ExtY(1), 8)
		STORF(idx_start_outputs + 1) = REAL(ExtY(2), 8)
		STORF(idx_start_outputs + 2) = REAL(ExtY(3), 8)

		Step_Count_Model = Step_Count_Model + 1
		Next_t_model = Step_Count_Model * DELT_Model
	END DO

	! --------------------------------
	! Persist state
	! --------------------------------
	STORI(idx_start_first_step_model) = merge(1, 0, First_Step_Model)
	STORI(idx_start_step_count_model) = Step_Count_Model

	! Get prev_t (previous time value of pscad) and previous values of pscad inputs
	IF (Use_Interpolation) THEN
		Prev_t_pscad = STORF(idx_start_prev_t)
		in_voltage_a_pscad_prev = STORF(idx_start_inputs + 0)
		in_voltage_b_pscad_prev = STORF(idx_start_inputs + 1)
		in_voltage_c_pscad_prev = STORF(idx_start_inputs + 2)
		in_current_a_pscad_prev = STORF(idx_start_inputs + 3)
		in_current_b_pscad_prev = STORF(idx_start_inputs + 4)
		in_current_c_pscad_prev = STORF(idx_start_inputs + 5)
	ENDIF

	! Inputs and TIME into STORF (kept for interpolation on the next step)
	IF (Use_Interpolation) THEN
		STORF(idx_start_prev_t) = TIME
		STORF(idx_start_inputs + 0) = in_voltage_a_pscad
		STORF(idx_start_inputs + 1) = in_voltage_b_pscad
		STORF(idx_start_inputs + 2) = in_voltage_c_pscad
		STORF(idx_start_inputs + 3) = in_current_a_pscad
		STORF(idx_start_inputs + 4) = in_current_b_pscad
		STORF(idx_start_inputs + 5) = in_current_c_pscad
	ENDIF

	! --------------------------------
	! Send outputs back to PSCAD (from STORF, so this also works on
	! sub-steps where the DO WHILE loop above did not execute)
	! --------------------------------
	out_voltage_a_pscad = STORF(idx_start_outputs + 0)
	out_voltage_b_pscad = STORF(idx_start_outputs + 1)
	out_voltage_c_pscad = STORF(idx_start_outputs + 2)

	! --------------------------------
	! Cleanup on the last time step
	! --------------------------------
	IF (LASTSTEP) THEN
		pInstanceCapi = Ints_To_CPtr(STORI(idx_start_instance_ptr:idx_start_instance_ptr+1))
		IF (c_associated(pInstanceCapi)) THEN
			msg_cptr = Model_Terminate(pInstanceCapi)
			call Handle_Message("Model_Terminate", msg_cptr)
		ENDIF

		N_CALL_LAST_STEP = N_CALL_LAST_STEP + 1
		IF (N_CALL_LAST_STEP .EQ. N_INSTANCE) THEN
			retValFreeLib = FreeLibrary(dllHandle)
			dllHandle = 0
			FIRST_CALL_THIS_FILE = .TRUE.
			N_INSTANCE = 0
			N_CALL_LAST_STEP = 0
		ENDIF
	ENDIF

	! --------------------------------
	! Advance STORx pointers for the next model instance in the file
	! --------------------------------
	NSTORI = idx_start_next_model_stori

	NSTORF = idx_start_next_model_storf

	END

